services:
  postgres:
    image: postgres:16
    container_name: pharmacy-db
    restart: always
    environment:
      POSTGRES_USER: pharmacy
      POSTGRES_PASSWORD: pharmacy
      POSTGRES_DB: pharmacy_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
